import React, { forwardRef } from "react";
import { useGLTF } from "@react-three/drei";

const AstonMartinDB11 = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF('/gltf/Aston Martin DB11.gltf');
  
  return (
    <group ref={ref} {...props} dispose={null}>
      <group position={[-0.81, 0.33, -1.38]} rotation={[0, 0, Math.PI]} scale={[-1, -1, -1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheels002.geometry}
          material={nodes.wheels002.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheels002_1.geometry}
          material={nodes.wheels002_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheels002_2.geometry}
          material={nodes.wheels002_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheels002_3.geometry}
          material={nodes.wheels002_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheels002_4.geometry}
          material={nodes.wheels002_4.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheels002_5.geometry}
          material={nodes.wheels002_5.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheels002_6.geometry}
          material={nodes.wheels002_6.material}
        />
      </group>
      <group position={[0.81, 0.33, -1.38]} rotation={[0, 0, Math.PI]} scale={[-1, -1, -1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheels.geometry}
          material={nodes.wheels.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheels_1.geometry}
          material={nodes.wheels_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheels_2.geometry}
          material={nodes.wheels_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheels_3.geometry}
          material={nodes.wheels_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheels_4.geometry}
          material={nodes.wheels_4.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheels_5.geometry}
          material={nodes.wheels_5.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheels_6.geometry}
          material={nodes.wheels_6.material}
        />
      </group>
      <group position={[-0.83, 0.33, 1.42]} rotation={[0, 0, Math.PI]} scale={[-1, -1, -1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheels003.geometry}
          material={nodes.wheels003.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheels003_1.geometry}
          material={nodes.wheels003_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheels003_2.geometry}
          material={nodes.wheels003_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheels003_3.geometry}
          material={nodes.wheels003_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheels003_4.geometry}
          material={nodes.wheels003_4.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheels003_5.geometry}
          material={nodes.wheels003_5.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheels003_6.geometry}
          material={nodes.wheels003_6.material}
        />
      </group>
      <group position={[0.83, 0.33, 1.42]} scale={[-1, -1, -1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheels001.geometry}
          material={nodes.wheels001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheels001_1.geometry}
          material={nodes.wheels001_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheels001_2.geometry}
          material={nodes.wheels001_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheels001_3.geometry}
          material={nodes.wheels001_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheels001_4.geometry}
          material={nodes.wheels001_4.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheels001_5.geometry}
          material={nodes.wheels001_5.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheels001_6.geometry}
          material={nodes.wheels001_6.material}
        />
      </group>
      <group position={[-0.39, 0.84, -0.28]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Speedo_actually_RPM_Needle.geometry}
          material={materials['Speedo [actually RPM] Needle']}
          position={[0.39, -0.26, 0.29]}
        />
      </group>
      <group position={[0, 0.58, 0.02]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lights.geometry}
          material={nodes.lights.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lights_1.geometry}
          material={nodes.lights_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lights_2.geometry}
          material={nodes.lights_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lights_3.geometry}
          material={nodes.lights_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lights_4.geometry}
          material={nodes.lights_4.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lights_5.geometry}
          material={nodes.lights_5.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lights_6.geometry}
          material={materials['Low Beams']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lights_7.geometry}
          material={materials['High Beams']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lights_8.geometry}
          material={materials['Day Lights']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lights_9.geometry}
          material={nodes.lights_9.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lights_10.geometry}
          material={materials.Taillights}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lights_11.geometry}
          material={nodes.lights_11.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lights_12.geometry}
          material={nodes.lights_12.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chassis_Bolts.geometry}
        material={nodes.Chassis_Bolts.material}
        position={[0, 0.58, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Right_Door_Buttons.geometry}
        material={nodes.Right_Door_Buttons.material}
        position={[0, 0.58, 0.92]}
      />
      <group position={[0, 0.58, 0.02]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.chassis_ok.geometry}
          material={nodes.chassis_ok.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.chassis_ok_1.geometry}
          material={nodes.chassis_ok_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.chassis_ok_2.geometry}
          material={nodes.chassis_ok_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.chassis_ok_3.geometry}
          material={nodes.chassis_ok_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.chassis_ok_4.geometry}
          material={nodes.chassis_ok_4.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rear_Right_Brake_Caliper.geometry}
        material={nodes.Rear_Right_Brake_Caliper.material}
        position={[0.82, 0.32, 1.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rear_Left_Brake_Caliper.geometry}
        material={nodes.Rear_Left_Brake_Caliper.material}
        position={[-0.82, 0.32, 1.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Front_Left_Brake_Caliper.geometry}
        material={nodes.Front_Left_Brake_Caliper.material}
        position={[0, 0.58, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Front_Brake_Caliper.geometry}
        material={nodes.Front_Brake_Caliper.material}
        position={[0.81, 0.33, -1.38]}
      />
      <group position={[0, 0.58, 0.02]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.enginebay.geometry}
          material={nodes.enginebay.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.enginebay_1.geometry}
          material={nodes.enginebay_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.enginebay_2.geometry}
          material={nodes.enginebay_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.enginebay_3.geometry}
          material={nodes.enginebay_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.enginebay_4.geometry}
          material={materials.Misc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.enginebay_5.geometry}
          material={nodes.enginebay_5.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.enginebay_6.geometry}
          material={nodes.enginebay_6.material}
        />
      </group>
      <group position={[0, 0.58, 0.02]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bump_front_ok.geometry}
          material={nodes.bump_front_ok.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bump_front_ok_1.geometry}
          material={nodes.bump_front_ok_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bump_front_ok_2.geometry}
          material={nodes.bump_front_ok_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bump_front_ok_3.geometry}
          material={nodes.bump_front_ok_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bump_front_ok_4.geometry}
          material={nodes.bump_front_ok_4.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bump_front_ok_5.geometry}
          material={nodes.bump_front_ok_5.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bump_front_ok_6.geometry}
          material={materials.Splitter}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bump_front_ok_7.geometry}
          material={nodes.bump_front_ok_7.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bump_front_ok_8.geometry}
          material={nodes.bump_front_ok_8.material}
        />
      </group>
      <group position={[0, 0.55, -2.32]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bonnet_ok.geometry}
          material={nodes.bonnet_ok.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bonnet_ok_1.geometry}
          material={nodes.bonnet_ok_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bonnet_ok_2.geometry}
          material={nodes.bonnet_ok_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bonnet_ok_3.geometry}
          material={nodes.bonnet_ok_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bonnet_ok_4.geometry}
          material={nodes.bonnet_ok_4.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bonnet_ok_5.geometry}
          material={nodes.bonnet_ok_5.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bonnet_ok_6.geometry}
          material={nodes.bonnet_ok_6.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bonnet_ok_7.geometry}
          material={materials.Gray}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Front_License_Plate.geometry}
        material={nodes.Front_License_Plate.material}
        position={[0, 0.58, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Radiator_Fan.geometry}
        material={nodes.Radiator_Fan.material}
        position={[0, 0.58, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Engine_Bay_Bolts.geometry}
        material={nodes.Engine_Bay_Bolts.material}
        position={[0, 0.58, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Glass.geometry}
        material={nodes.Glass.material}
        position={[0, 0.58, 0.02]}
      />
      <group position={[0, 0.58, 0.02]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.engine.geometry}
          material={nodes.engine.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.engine_1.geometry}
          material={nodes.engine_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.engine_2.geometry}
          material={materials.Hoses}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.engine_3.geometry}
          material={materials['Hose Clamps']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.engine_4.geometry}
          material={materials['Aston Martin DB11 Signature']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.engine_5.geometry}
          material={materials['Engine Yellow']}
        />
      </group>
      <group position={[0, 0.58, 0.02]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.engine_badge.geometry}
          material={nodes.engine_badge.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.engine_badge_1.geometry}
          material={nodes.engine_badge_1.material}
        />
      </group>
      <group position={[0, 0.58, 0.02]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.interior.geometry}
          material={nodes.interior.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.interior_1.geometry}
          material={nodes.interior_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.interior_2.geometry}
          material={nodes.interior_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.interior_3.geometry}
          material={nodes.interior_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.interior_4.geometry}
          material={nodes.interior_4.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.interior_5.geometry}
          material={materials.Carpet}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.interior_6.geometry}
          material={nodes.interior_6.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.interior_7.geometry}
          material={materials['Dashboard [Put any color you want, even leather]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.interior_8.geometry}
          material={materials.Alcantara}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.interior_9.geometry}
          material={materials['Headliner [any color you want]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.interior_10.geometry}
          material={nodes.interior_10.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.interior_11.geometry}
          material={nodes.interior_11.material}
        />
      </group>
      <group position={[0, 0.58, 0.91]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_lf_ok.geometry}
          material={nodes.door_lf_ok.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_lf_ok_1.geometry}
          material={nodes.door_lf_ok_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_lf_ok_2.geometry}
          material={nodes.door_lf_ok_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_lf_ok_3.geometry}
          material={nodes.door_lf_ok_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_lf_ok_4.geometry}
          material={nodes.door_lf_ok_4.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_lf_ok_5.geometry}
          material={nodes.door_lf_ok_5.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Left_Door_Buttons.geometry}
          material={nodes.Left_Door_Buttons.material}
          position={[0, 0, 0.02]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.glass_lf_ok.geometry}
          material={nodes.glass_lf_ok.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.glass_lf_ok_1.geometry}
          material={nodes.glass_lf_ok_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.glass_lf_ok_2.geometry}
          material={nodes.glass_lf_ok_2.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Windscreen_Wiper.geometry}
        material={nodes.Windscreen_Wiper.material}
        position={[0, 0.58, 0.02]}
      />
      <group position={[0, 0.58, 0.02]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.badge.geometry}
          material={nodes.badge.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.badge_1.geometry}
          material={nodes.badge_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.badge_2.geometry}
          material={nodes.badge_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.badge_3.geometry}
          material={nodes.badge_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.badge_4.geometry}
          material={materials['Stitch 2']}
        />
      </group>
      <group position={[0, 0.58, 0.02]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.decals.geometry}
          material={nodes.decals.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.decals_1.geometry}
          material={materials.Screen}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.decals_2.geometry}
          material={materials.Gauges}
        />
      </group>
      <group position={[0, 0.58, 0.91]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_lf_ok001.geometry}
          material={nodes.door_lf_ok001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_lf_ok001_1.geometry}
          material={nodes.door_lf_ok001_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_lf_ok001_2.geometry}
          material={nodes.door_lf_ok001_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_lf_ok001_3.geometry}
          material={nodes.door_lf_ok001_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_lf_ok001_4.geometry}
          material={nodes.door_lf_ok001_4.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_lf_ok001_5.geometry}
          material={nodes.door_lf_ok001_5.material}
        />
      </group>
      <group position={[0, 0.58, 0.02]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.movsteer_05.geometry}
          material={nodes.movsteer_05.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.movsteer_05_1.geometry}
          material={nodes.movsteer_05_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.movsteer_05_2.geometry}
          material={nodes.movsteer_05_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.movsteer_05_3.geometry}
          material={nodes.movsteer_05_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.movsteer_05_4.geometry}
          material={nodes.movsteer_05_4.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.movsteer_05_5.geometry}
          material={nodes.movsteer_05_5.material}
        />
      </group>
      <group position={[0, 0.58, 0.02]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.seat.geometry}
          material={nodes.seat.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.seat_1.geometry}
          material={nodes.seat_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.seat_2.geometry}
          material={nodes.seat_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.seat_3.geometry}
          material={nodes.seat_3.material}
        />
      </group>
      <group position={[0, 0.58, 0.91]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.glass_rf_ok.geometry}
          material={nodes.glass_rf_ok.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.glass_rf_ok_1.geometry}
          material={nodes.glass_rf_ok_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.glass_rf_ok_2.geometry}
          material={nodes.glass_rf_ok_2.material}
        />
      </group>
      <group position={[0, 0.58, 0.02]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bump_rear_ok.geometry}
          material={nodes.bump_rear_ok.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bump_rear_ok_1.geometry}
          material={nodes.bump_rear_ok_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bump_rear_ok_2.geometry}
          material={nodes.bump_rear_ok_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bump_rear_ok_3.geometry}
          material={nodes.bump_rear_ok_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bump_rear_ok_4.geometry}
          material={nodes.bump_rear_ok_4.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bump_rear_ok_5.geometry}
          material={nodes.bump_rear_ok_5.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bump_rear_ok_6.geometry}
          material={nodes.bump_rear_ok_6.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bump_rear_ok_7.geometry}
          material={nodes.bump_rear_ok_7.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bump_rear_ok_8.geometry}
          material={nodes.bump_rear_ok_8.material}
        />
      </group>
      <group position={[0, 0.58, 0.02]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.exhaust.geometry}
          material={nodes.exhaust.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.exhaust_1.geometry}
          material={nodes.exhaust_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.exhaust_2.geometry}
          material={nodes.exhaust_2.material}
        />
      </group>
      <group position={[0, 0.58, 0.02]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.boot_ok_1.geometry}
          material={nodes.boot_ok_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.boot_ok_2.geometry}
          material={nodes.boot_ok_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.boot_ok_3.geometry}
          material={nodes.boot_ok_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.boot_ok_4.geometry}
          material={nodes.boot_ok_4.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.boot_ok_5.geometry}
          material={nodes.boot_ok_5.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.boot_ok_6.geometry}
          material={nodes.boot_ok_6.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.boot_ok_7.geometry}
          material={nodes.boot_ok_7.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.boot_ok_8.geometry}
          material={nodes.boot_ok_8.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.boot_ok_9.geometry}
          material={nodes.boot_ok_9.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rear_License_Plate.geometry}
        material={nodes.Rear_License_Plate.material}
        position={[0, 0.58, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trunk_Taillight_Glass.geometry}
        material={nodes.Trunk_Taillight_Glass.material}
        position={[0, 0.58, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trunk_Bolts.geometry}
        material={nodes.Trunk_Bolts.material}
        position={[0, 0.58, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Spoiler.geometry}
        material={nodes.Spoiler.material}
        position={[0, 0.58, 0.02]}
      />
    </group>
  )
});

useGLTF.preload('/gltf/Aston Martin DB11.gltf');

export default AstonMartinDB11;
